language: erlang
otp_release:
- 17.1
env:
- ELIXIR_VERSION=1.0.0
before_install:
- cd /tmp
- wget https://github.com/elixir-lang/elixir/releases/download/v$ELIXIR_VERSION/Precompiled.zip
- unzip Precompiled.zip
- export PATH="$PWD/bin:$PATH"
- cd -
script:
- mix test